/low_light_down_misp_encoded:
  reliability: reliable
  durability: transient_local
  history: keep_last
  depth: 10

/tracking_down_misp_encoded:
  reliability: reliable
  durability: transient_local
  history: keep_last
  depth: 10

/tracking_front_misp_encoded:
  reliability: reliable
  durability: transient_local
  history: keep_last
  depth: 10