/low_light_down_misp_encoded:
  reliability: reliable
  durability: transient_local
  history: keep_last
  depth: 30

/tracking_down_misp_encoded:
  reliability: reliable
  durability: transient_local
  history: keep_last
  depth: 30

/tracking_front_misp_encoded:
  reliability: reliable
  durability: transient_local
  history: keep_last
  depth: 30

/hires_down_small_encoded:
  reliability: reliable
  durability: transient_local
  history: keep_last
  depth: 30

/hires_front_small_encoded:
  reliability: reliable
  durability: transient_local
  history: keep_last
  depth: 30

/ircam/h264:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 30